BEGIN TRANSACTION;
DROP TABLE IF EXISTS `UserSession`;
CREATE TABLE IF NOT EXISTS `UserSession` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`userId`	INTEGER NOT NULL,
	`token`	TEXT NOT NULL UNIQUE,
	`expiry`	TEXT NOT NULL
);
DROP TABLE IF EXISTS `UserMood`;
CREATE TABLE IF NOT EXISTS `UserMood` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`date`	TEXT NOT NULL,
	`userId`	INTEGER NOT NULL,
	`moodId`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `User`;
CREATE TABLE IF NOT EXISTS `User` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`firstName`	TEXT NOT NULL,
	`lastName`	TEXT NOT NULL,
	`username`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`email`	TEXT
);
DROP TABLE IF EXISTS `Mood`;
CREATE TABLE IF NOT EXISTS `Mood` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`color`	TEXT NOT NULL,
	`description`	TEXT
);
COMMIT;
