BEGIN TRANSACTION;
INSERT INTO `UserMood` VALUES (1,'10/14/2017',1,3);
INSERT INTO `UserMood` VALUES (2,'10/13/2017',1,1);
INSERT INTO `UserMood` VALUES (3,'10/13/2017',2,1);
INSERT INTO `User` VALUES (1,'Wes','Miravete','averagewizard','$2b$12$n7tndX0nWpgMKNVdwy0iQ.uZrOlgJDgk.H7BdqMZem5IAR8k/chEK','');
INSERT INTO `User` VALUES (2,'Maryn','Weed','mweed','$2b$12$n7tndX0nWpgMKNVdwy0iQ.uZrOlgJDgk.H7BdqMZem5IAR8k/chEK',NULL);
INSERT INTO `User` VALUES (3,'Simon','Oliver','olimon','$2b$12$n7tndX0nWpgMKNVdwy0iQ.uZrOlgJDgk.H7BdqMZem5IAR8k/chEK',NULL);
INSERT INTO `User` VALUES (4,'Captain','Miravete','captain','$2b$12$n7tndX0nWpgMKNVdwy0iQ.uZrOlgJDgk.H7BdqMZem5IAR8k/chEK',NULL);
INSERT INTO `Mood` VALUES (1,'Happy','#A9EF12',NULL);
INSERT INTO `Mood` VALUES (2,'Sad','#4E12EF',NULL);
INSERT INTO `Mood` VALUES (3,'Neutral','#A2EDDF',NULL);
COMMIT;
